<?php
/**
 * =============================================================
 * @file        $Id: analytics.php 1.7 2012-06-28 00:00:00 Luiz Felipe Weber $
 * @package	    Analytics 
 * @version     1.7
 * @class name  Analytics (Controller)
 * @description Componente Analytics Webgenium. Este componente é uma implementação do com_analytics. Possui algumas funcionalidades a mais, como gráfico animado, tradução em pt-br e mostra as estatísticas do Google Analytics do site cadastrado de uma forma mais rápida e totalmente integrada.
 * @copyright	  Copyright © 2012 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Luiz Felipe Weber
 * @author mail	suporte@webgenium.com.br
 * @website		  http://webgenium.com.br
 * =============================================================
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 */

// No direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

jimport('joomla.application.component.controller');

/**
 * Controller class
 */
class analyticsControllerAnalytics extends analyticsController
{



	/**
	 * constructor (registers additional tasks to methods)
	 * @return void
	 */
	function __construct()
	{
		parent::__construct();

    // Register Extra tasks
		// $this->registerTask( 'new' , 'save' );
	
	}  
	
} // end Controller class
?>